add controllers
elbonreedZ/filmorate pull request #3
Opened 2024-06-05 00:16 UTC by elbonreedZ

2024-06-05 19:50 UTC, YazykovMikhail requested changes

2024-06-05 19:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private int getNextId() {
Где показывают такой код?) Второй раз вижу. 
представь что у тебя 1000000000 обьектов хранится, представляешь каждый раз по всем пробегать и высчитывать максимальное id
Сделай как мы делали в TaskManager просто сделай поле которое будет счетчиком и увеличивай его

2024-06-05 19:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private int getNextId() {
Аналогично для User

2024-06-05 19:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Collection<Film> getAll() {
Возвраащай все тки List<Film>, Collection слишком абстрактно, а так понятно что список

Логирование тоже нужно

2024-06-05 19:50 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Collection<Film> getAll() {
Аналогично для User

2024-06-08 14:06 UTC, elbonreedZ commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private int getNextId() {
ахахах да, я понимаю. Это в проекте втором кетсграмме авторы сами вот это вот написали. Ну я решила оставить тут такое, подумала, что может есть этому хоть какое-то обьяснение, раз раз авторы сами такое предложили

2024-06-09 09:21 UTC, YazykovMikhail approved these changes

2024-06-09 09:21 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    }
Логирование ответа тое должно быть, иначе как потом понять что вернул метод и где искать ошибку?

2024-06-09 09:53 UTC, elbonreedZ commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    }
Не поняла, там же одна строчка с возвратом я не могу после лог написать

2024-06-30 20:27 UTC, merged