Add database
elbonreedZ/filmorate pull request #7
Opened 2024-08-14 18:45 UTC by elbonreedZ

2024-08-15 16:09 UTC, YazykovMikhail commented
Обрати увнимание, что тесты не прошли, бещ пройденых тестов возможности проверять у нас к сожалению нет

2024-09-02 18:39 UTC, YazykovMikhail requested changes

2024-09-02 18:39 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film like(@PathVariable long id, @PathVariable long userId) {
Раз ты ввела дто - и это верно, то везде на вход и выход и выход в контроллерах должно дыть дто

2024-09-02 18:39 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film like(@PathVariable long id, @PathVariable long userId) {
По правельному, если контракты в эндпотинтах отличаются, то должны быть разные дто для каждого метода, но в этой размете требовать не будут.
Вообшем раз ввела дто, то стоит сделать на вход и выход их, только это не должнен быть один класс
Один на вход, другой на выход - это если делать прям норм, если не хочеш ьпока заморачиваться сейчас это не обяазтельно

2024-09-02 18:39 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +    long id;
private

2024-09-02 18:39 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Rating.java
> +    long id;
private

2024-09-02 18:39 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          log.info("Возврат списка всех фильмов: {}", filmStorage.getAll());
Обрати внимание что у тебя тут двое обращние в хранилище
и также логировать стоит после полкчения списка а не до

2024-09-02 18:39 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/dal/GenresDbStorage.java
> +public class GenresDbStorage extends BaseDbStorage<Genre> {
Для каждего репозитория должен быть свой интерфйес

2024-09-02 18:39 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/dal/FilmDbStorage.java
> +    public Optional<Film> getById(long id) {
А как же рейтинг МПА?

2024-09-02 18:39 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/dal/FilmDbStorage.java
> +    public Optional<Film> getById(long id) {
Смотри, при получении всех фильмов ты делаешь 1 запрос на получение всех полей через 
LEFT JOIN, так же стоит делать и тут

2024-09-02 18:39 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/dal/FilmDbStorage.java
> +    private final LikesDbStorage likesDbStorage;
Репозитории не должны никуда ходить, ни в какие другие репозитории. 
Все запросы делаются средствами sql, а для связи многие ко многим, они вызываюся из сервиса

2024-09-04 21:25 UTC, elbonreedZ commented on src/main/java/ru/yandex/practicum/filmorate/storage/dal/FilmDbStorage.java
> +    private final LikesDbStorage likesDbStorage;
имеете в виду сделать сервис для лайков отдельный?

2024-09-26 22:53 UTC, merged